

# Optionally: LangSmith secrets for tracing
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = "test-ls-lc"

# Astra Vector Secrets

ASTRA_VECTOR_ENDPOINT =""
ASTRA_DB_APPLICATION_TOKEN = ""
AWS_ACCESS_KEY_ID=''
AWS_SECRET_ACCESS_KEY=''
AWS_DEFAULT_REGION='us-east-1'

[passwords]
# Follow the rule: username = "password"
# Where username defines the Astra Vector Table and the rails.csv experience
postnl = "password_xyz"
datastax = "password_abc"


[languages]
# Follow the rule: username = "localization_code"
# Where localization_code defines the language from localization.csv
postnl = "nl_NL"
datastax = "en_US"

[delete_option]
# Follow the rule: username = "delete_option"
# Where delete_option = True allows the 'Delete Context' button to be shown for that username
michel = "True"
